name: "front build pipeline"

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout front folder
        uses: Bhacaz/checkout-files@v1
        with:
          files: front
          token: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: mfurones.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_APIKEY }}

      - name: GitHub Action for Bash
        run: |
          pwd &&
          ls -la

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: docker-mfpage
          context: ./front/
          file: ./dockerFile/dockerfile
          push: true
          tags: |
            front/frontapp:latest






