name: "front build pipeline"

on:
  workflow_dispatch:
    inputs:
          name:
            description: 'Manual Trigger'
            required: true
            default: 'run'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout front folder
        uses: Bhacaz/checkout-files@v1
        with:
          files: front
          token: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: mfurones.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_APIKEY }}

      - name: GitHub Action for Bash
        uses: jcblw/bash@master
        args: ["ls -la"]

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: docker-mfpage
          context: ./
          file: ./dockerFile/dockerfile
          push: true
          tags: |
            front/frontapp:latest






